### ISSUE TITLE
Insights link broken on about page

### ISSUE THREAD

**Issue by philipkershaw** [cedadev/jasmin-site-jekyll#5]
https://jasmin.ac.uk/insights gives page not found from https://jasmin.ac.uk/about/

**Comment by mjpritchard** [comment]
Probably going to ditch the insights page (pending discussion with Poppy).
Thoughts:
* cater for by posts within CEDA tech blog (tag as relevant to jasmin?)
* cater for by jasmin site's own blog/post section with "insights" articles
  * but needs ongoing effort to source relevant articles
* if ditching, need to remove link to it on about page.
